name: foldflow-env
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - libstdcxx-ng
  - mdtraj
  - pip
  - pip:
      - biopython
      - click
      - corner
      - debugpy
      - dm-tree
      - einops
      - e3nn==0.5.6
      - fair-esm
      - git+https://github.com/joeybose/geomstats.git
      - gputil
      - hydra-core
      - hydra-joblib-launcher
      - ipdb
      - jupyterlab
      - lmdb
      - lightning==2.5.1
      - ml-collections
      - numpy
      - pandas
      - pot
      - plotly
      - pytest
      - seaborn
      - tmtools
      - tqdm
      - wandb>=0.15.1
      - OpenMM
      - pydantic
      - pytorch_lightning==2.5.1
      - biotite
      - torch_scatter
      - torch_sparse
      - torch_cluster
      - --find-links https://data.pyg.org/whl/torch-2.4.0+cu124.html
      - torch_geometric==2.6.1
  - pip:
      - torch==2.4.0
      - torchvision==0.19.0
      - --index-url https://download.pytorch.org/whl/cu124
      - -e .
