# Default or base configuration for SE(3) Flow Matcher experiments.
defaults:
  - data: data_test
  - flow_matcher: fm_test
  - model: ff2
  - experiment: exp_test
  - local: ff2_debug
  - wandb: default
  - override hydra/launcher: joblib
  - _self_

    # start_time_string: ${now:%Y-%m-%d}_${now:%H-%M-%S}
start_time_string: "default"
conda_env: foldflow-env
