# Default or base configuration for SE(3) Flow Matcher experiments.
defaults:
  - data: default
  - flow_matcher: default
  - model: ff2_mace
  - experiment: baseline
  - local: ff2_mace
  - wandb: default
  - override hydra/launcher: joblib
  - _self_

    # start_time_string: ${now:%Y-%m-%d}_${now:%H-%M-%S}
start_time_string: "default"
conda_env: foldflow-env
